# Copyright (C) 2012 The CyanogenMod Project
# Copyright (C) 2015 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/zerofltetmo/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/zerofltetmo/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/zerofltetmo/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/samsung/zerofltetmo/proprietary/vendor/firmware/bcm4358A3_V0028.0044.hcd:system/vendor/firmware/bcm4358A3_V0028.0044.hcd \
    vendor/samsung/zerofltetmo/proprietary/vendor/firmware/mcRegistry/08880000000000000000000000000000.tlbin:system/vendor/firmware/mcRegistry/08880000000000000000000000000000.tlbin
