# Copyright (C) 2015 The CyanogenMod Project
# Copyright (C) 2015 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/zerofltespr/setup-makefiles.sh

## zerofltespr/device-proprietary-blobs.txt
PRODUCT_COPY_FILES += \
	vendor/samsung/zerofltespr/proprietary/app/mcRegistry/ffffffff000000000000000000000028.tlbin:system/app/mcRegistry/ffffffff000000000000000000000028.tlbin \
	vendor/samsung/zerofltespr/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libsec-ril.so:system/lib64/libsec-ril.so \
	vendor/samsung/zerofltespr/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
	vendor/samsung/zerofltespr/proprietary/bin/argosd:system/bin/argosd \
	vendor/samsung/zerofltespr/proprietary/bin/at_distributor:system/bin/at_distributor \
	vendor/samsung/zerofltespr/proprietary/bin/connfwexe:system/bin/connfwexe \
	vendor/samsung/zerofltespr/proprietary/bin/ddexe:system/bin/ddexe \
	vendor/samsung/zerofltespr/proprietary/bin/diagexe:system/bin/diagexe \
	vendor/samsung/zerofltespr/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
	vendor/samsung/zerofltespr/proprietary/bin/diag_uart_log:system/bin/diag_uart_log \
	vendor/samsung/zerofltespr/proprietary/bin/irsc_util:system/bin/irsc_util \
	vendor/samsung/zerofltespr/proprietary/bin/ks:system/bin/ks \
	vendor/samsung/zerofltespr/proprietary/bin/mdm_helper:system/bin/mdm_helper \
	vendor/samsung/zerofltespr/proprietary/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
	vendor/samsung/zerofltespr/proprietary/bin/qmiproxy:system/bin/qmiproxy \
	vendor/samsung/zerofltespr/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/samsung/zerofltespr/proprietary/bin/rtc_log.sh:system/bin/rtc_log.sh \
	vendor/samsung/zerofltespr/proprietary/bin/umount:system/bin/umount \
	vendor/samsung/zerofltespr/proprietary/etc/sec_s3fwrn5s_rfreg_for_old_hw.bin:system/etc/sec_s3fwrn5s_rfreg_for_old_hw.bin \
	vendor/samsung/zerofltespr/proprietary/etc/sec_config:system/etc/sec_config \
	vendor/samsung/zerofltespr/proprietary/etc/Diag.cfg:system/etc/Diag.cfg \
	vendor/samsung/zerofltespr/proprietary/etc/Diag_zero.cfg:system/etc/Diag_zero.cfg \
	vendor/samsung/zerofltespr/proprietary/lib/libatparser.so:system/lib/libatparser.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libatparser.so:system/lib64/libatparser.so \
	vendor/samsung/zerofltespr/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
	vendor/samsung/zerofltespr/proprietary/lib/libchameleon.so:system/lib/libchameleon.so \
	vendor/samsung/zerofltespr/proprietary/lib/libcordon.so:system/lib/libcordon.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libcordon.so:system/lib64/libcordon.so \
	vendor/samsung/zerofltespr/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libcsd-client.so:system/lib64/libcsd-client.so \
	vendor/samsung/zerofltespr/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libfactoryutil.so:system/lib64/libfactoryutil.so \
	vendor/samsung/zerofltespr/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libomission_avoidance.so:system/lib64/libomission_avoidance.so \
	vendor/samsung/zerofltespr/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
	vendor/samsung/zerofltespr/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libmdmdetect.so:system/lib64/libmdmdetect.so \
	vendor/samsung/zerofltespr/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
	vendor/samsung/zerofltespr/proprietary/lib64/librmnetctl.so:system/lib64/librmnetctl.so \
	vendor/samsung/zerofltespr/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libreference-ril.so:system/lib64/libreference-ril.so \
	vendor/samsung/zerofltespr/proprietary/lib/libssaudio-client.so:system/lib/libssaudio-client.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libssaudio-client.so:system/lib64/libssaudio-client.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libcfiril.so:system/lib64/libcfiril.so \
	vendor/samsung/zerofltespr/proprietary/lib64/librilswitch.so:system/lib64/librilswitch.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libxml.so:system/lib64/libxml.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so\
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
	vendor/samsung/zerofltespr/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so
